name = "recommendations-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "recommendations-db"
database_id = "49c68912-ce6e-4899-8e73-8955a6a21dee"
